/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2022-04-11 03:26:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Agricultural Web Portal</title>\r\n");
      out.write("<!-- google fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css2?family=Poppins:wght@300;600;700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- google fonts -->\r\n");
      out.write("<!-- Template CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style-starter.css\">\r\n");
      out.write("<!-- Template CSS -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--header-->\r\n");
      out.write("\t<header id=\"site-header\" class=\"fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "design-side-header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- //header -->\r\n");
      out.write("\t<!-- about breadcrumb -->\r\n");
      out.write("\t<section class=\"w3l-about-breadcrumb text-left\">\r\n");
      out.write("\t\t<div class=\"breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4\">\r\n");
      out.write("\t\t\t<div class=\"container py-2\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title\">About Us</h2>\r\n");
      out.write("\t\t\t\t<ul class=\"breadcrumbs-custom-path mt-2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#url\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><span class=\"fa fa-arrow-right mx-2\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\"></span> About</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //about breadcrumb -->\r\n");
      out.write("\t<!-- /about-6-->\r\n");
      out.write("\t<section class=\"w3l-cta4 py-5\">\r\n");
      out.write("\t\t<div class=\"container py-lg-5\">\r\n");
      out.write("\t\t\t<div class=\"ab-section\">\r\n");
      out.write("\t\t\t\t<h6 class=\"sub-title\">About Us</h6>\r\n");
      out.write("\t\t\t\t<h3 class=\"hny-title\">Agricultural System</h3>\r\n");
      out.write("\t\t\t\t<p class=\"py-3\">The Agricultural web portal to override the\r\n");
      out.write("\t\t\t\t\tproblems prevailing in the practicing manual system. This software\r\n");
      out.write("\t\t\t\t\tis supported to eliminate and in some cases reduce the hardships\r\n");
      out.write("\t\t\t\t\tfaced by this existing system. Moreover this system is designed for\r\n");
      out.write("\t\t\t\t\tthe particular need of the company to carry out operations in a\r\n");
      out.write("\t\t\t\t\tsmooth and effective manner.</p>\r\n");
      out.write("\t\t\t\t<p class=\"py-3\">The application is reduced as much as possible\r\n");
      out.write("\t\t\t\t\tto avoid errors while entering the data. It also provides error\r\n");
      out.write("\t\t\t\t\tmessage while entering invalid data. No formal knowledge is needed\r\n");
      out.write("\t\t\t\t\tfor the user to use this system. Thus by this all it proves it is\r\n");
      out.write("\t\t\t\t\tuser-friendly. Agricultural web portal, as described above, can\r\n");
      out.write("\t\t\t\t\tlead to error free, secure, reliable and fast management system. It\r\n");
      out.write("\t\t\t\t\tcan assist the user to concentrate on their other activities rather\r\n");
      out.write("\t\t\t\t\tto concentrate on the record keeping. Thus it will help\r\n");
      out.write("\t\t\t\t\torganization in better utilization of resources.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row mt-5\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 mt-md-0 mt-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"assets/images/banner1.jpg\" class=\"img-fluid\" alt=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //about-6-->\r\n");
      out.write("\t<!-- /content-6-->\r\n");
      out.write("\t<!-- //content-6-->\r\n");
      out.write("\t<!-- stats -->\r\n");
      out.write("\t<section class=\"w3l-statshny py-5\" id=\"stats\">\r\n");
      out.write("\t\t<div class=\"container py-lg-5 py-md-4\">\r\n");
      out.write("\t\t\t<div class=\"w3-stats-inner-info\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-6 stats_info counter_grid text-left\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-smile-o\"></span>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"counter\">1730</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>Happy Customers</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-6 stats_info counter_grid1 text-left\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-users\"></span>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"counter\">730</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>Custom Products</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-4 col-6 stats_info counter_grid mt-lg-0 mt-5 text-left\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-database\"></span>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"counter\">30</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>Branches</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //stats -->\r\n");
      out.write("\t<!-- team -->\r\n");
      out.write("\r\n");
      out.write("\t<!--/w3l-footer-29-main-->\r\n");
      out.write("\t<section class=\"w3l-footer-29-main\">\r\n");
      out.write("\t\t<div class=\"footer-29 py-5\">\r\n");
      out.write("\t\t\t<div class=\"container py-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"row footer-top-29\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-list-29 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"footer-title-29\">About Us</h6>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"pr-lg-5\">The Agricultural web portal to override the\r\n");
      out.write("\t\t\t\t\t\t\tproblems prevailing in the practicing manual system. This\r\n");
      out.write("\t\t\t\t\t\t\tsoftware is supported to eliminate and in some cases reduce the\r\n");
      out.write("\t\t\t\t\t\t\thardships faced by this existing system.</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-social-footer-29 mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#facebook\" class=\"facebook\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\"></span></a> <a href=\"#twitter\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"twitter\"><span class=\"fa fa-twitter\"></span></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#instagram\" class=\"instagram\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-instagram\"></span></a> <a href=\"#linkedin\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"linkedin\"><span class=\"fa fa-linkedin\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 col-sm-4 footer-list-29 footer-2 mt-lg-0 mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"footer-title-29\">Useful Links</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Crops</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Insecticides</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Pesticides</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Equipments</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-4 col-md-6 col-sm-8 footer-list-29 footer-1 mt-lg-0 mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"footer-title-29\">Contact Us</h6>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"fa fa-map-marker\"></span> Maharashtra, India\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"><span class=\"fa fa-phone\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+(91)-0000000000</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\" class=\"mail\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-envelope-open-o\"></span> agricultureinfo@mail.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section class=\"w3l-footer-29-main w3l-copyright\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"bottom-copies\">\r\n");
      out.write("\t\t\t\t<p class=\"copy-footer-29 text-center\">© 2022 Agricultural\r\n");
      out.write("\t\t\t\t\tSystem. All rights reserved.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- move top -->\r\n");
      out.write("\t\t<button onclick=\"topFunction()\" id=\"movetop\" title=\"Go to top\">\r\n");
      out.write("\t\t\t<span class=\"fa fa-angle-up\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t// When the user scrolls down 20px from the top of the document, show the button\r\n");
      out.write("\t\t\twindow.onscroll = function() {\r\n");
      out.write("\t\t\t\tscrollFunction()\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction scrollFunction() {\r\n");
      out.write("\t\t\t\tif (document.body.scrollTop > 20\r\n");
      out.write("\t\t\t\t\t\t|| document.documentElement.scrollTop > 20) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"movetop\").style.display = \"block\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"movetop\").style.display = \"none\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// When the user clicks on the button, scroll to the top of the document\r\n");
      out.write("\t\t\tfunction topFunction() {\r\n");
      out.write("\t\t\t\tdocument.body.scrollTop = 0;\r\n");
      out.write("\t\t\t\tdocument.documentElement.scrollTop = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- /move top -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //footer-29 block -->\r\n");
      out.write("\t<!-- disable body scroll which navbar is in active -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('.navbar-toggler').click(function() {\r\n");
      out.write("\t\t\t\t$('body').toggleClass('noscroll');\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- disable body scroll which navbar is in active -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template JavaScript -->\r\n");
      out.write("\t<script src=\"assets/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/theme-change.js\"></script>\r\n");
      out.write("\t<!-- stats number counter-->\r\n");
      out.write("\t<script src=\"assets/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.countup.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.counter').countUp();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //stats number counter -->\r\n");
      out.write("\t<!--/MENU-JS-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(window).on(\"scroll\", function() {\r\n");
      out.write("\t\t\tvar scroll = $(window).scrollTop();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (scroll >= 80) {\r\n");
      out.write("\t\t\t\t$(\"#site-header\").addClass(\"nav-fixed\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#site-header\").removeClass(\"nav-fixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//Main navigation Active Class Add Remove\r\n");
      out.write("\t\t$(\".navbar-toggler\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"header\").toggleClass(\"active\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"ready\", function() {\r\n");
      out.write("\t\t\tif ($(window).width() > 991) {\r\n");
      out.write("\t\t\t\t$(\"header\").removeClass(\"active\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(window).on(\"resize\", function() {\r\n");
      out.write("\t\t\t\tif ($(window).width() > 991) {\r\n");
      out.write("\t\t\t\t\t$(\"header\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--//MENU-JS-->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
