/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2022-02-03 14:53:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Agricultural Web Portal</title>\r\n");
      out.write("<!-- google fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//fonts.googleapis.com/css2?family=Poppins:wght@300;600;700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- google fonts -->\r\n");
      out.write("<!-- Template CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style-starter.css\">\r\n");
      out.write("<!-- Template CSS -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--header-->\r\n");
      out.write("\t<header id=\"site-header\" class=\"fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "design-side-header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //toggle switch for light and dark theme -->\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- //header -->\r\n");
      out.write("\t<!-- about breadcrumb -->\r\n");
      out.write("\t<section class=\"w3l-about-breadcrumb text-left\">\r\n");
      out.write("\t\t<div class=\"breadcrumb-bg breadcrumb-bg-about py-sm-5 py-4\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title\">Contact</h2>\r\n");
      out.write("\t\t\t\t<ul class=\"breadcrumbs-custom-path mt-2\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#url\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><span class=\"fa fa-arrow-right mx-2\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\"></span> Contact</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //about breadcrumb -->\r\n");
      out.write("\t<!-- /contact-->\r\n");
      out.write("\t<div class=\"contact-form py-5\" id=\"contact\">\r\n");
      out.write("\t\t<div class=\"container py-lg-5 py-md-4\">\r\n");
      out.write("\t\t\t<h3 class=\"hny-title mb-lg-5 mb-4\">Get in touch</h3>\r\n");
      out.write("\t\t\t<div class=\"contacts12-main mb-5\">\r\n");
      out.write("\t\t\t\t<form action=\"Contact\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"main-input\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"fullname\" id=\"w3lName\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Name\" class=\"contact-input\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" name=\"phone\" id=\"phone\" placeholder=\"Mobile Number\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"contact-input\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Your Email id\" class=\"contact-input\" required /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" name=\"subject\" id=\"subject\" placeholder=\"Subject\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"contact-input\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"contact-textarea\" name=\"message\" id=\"message\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Type your message here\" required></textarea>\r\n");
      out.write("\t\t\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-style btn-secondary btn-contact\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row pt-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contact-address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-color\"><span class=\"fa fa-map-marker\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>Maharashtra, India. </span></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mt-md-0 mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contact-address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-color\"><span class=\"fa fa-phone\"></span> <span><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"\" href=\"tel:+(91)-0000000000\">Phone\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t:+(91)-0000000000</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mt-lg-0 mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contact-address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-color\"><span class=\"fa fa-mail-reply\"></span><span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"mailto:agricultureinfo@mail.com\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tagricultureinfo@mail.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"maphny\">\r\n");
      out.write("\t\t<iframe\r\n");
      out.write("\t\t\tsrc=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387190.2895687731!2d-74.26055986835598!3d40.697668402590374!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY%2C+USA!5e0!3m2!1sen!2sin!4v1562582305883!5m2!1sen!2sin\"\r\n");
      out.write("\t\t\tframeborder=\"0\" style=\"border: 0\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/w3l-footer-29-main-->\r\n");
      out.write("\t<section class=\"w3l-footer-29-main\">\r\n");
      out.write("\t\t<div class=\"footer-29 py-5\">\r\n");
      out.write("\t\t\t<div class=\"container py-lg-4\">\r\n");
      out.write("\t\t\t\t<div class=\"row footer-top-29\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-list-29 col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"footer-title-29\">About Us</h6>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"pr-lg-5\">The Agricultural web portal to override the\r\n");
      out.write("\t\t\t\t\t\t\tproblems prevailing in the practicing manual system. This\r\n");
      out.write("\t\t\t\t\t\t\tsoftware is supported to eliminate and in some cases reduce the\r\n");
      out.write("\t\t\t\t\t\t\thardships faced by this existing system.</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main-social-footer-29 mt-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#facebook\" class=\"facebook\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-facebook\"></span></a> <a href=\"#twitter\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"twitter\"><span class=\"fa fa-twitter\"></span></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#instagram\" class=\"instagram\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-instagram\"></span></a> <a href=\"#linkedin\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"linkedin\"><span class=\"fa fa-linkedin\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-4 col-md-6 col-sm-4 footer-list-29 footer-2 mt-lg-0 mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"footer-title-29\">Useful Links</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Crops</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Insecticides</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Pesticides</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">Equipments</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"col-lg-4 col-md-6 col-sm-8 footer-list-29 footer-1 mt-lg-0 mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"footer-title-29\">Contact Us</h6>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"fa fa-map-marker\"></span> Maharashtra, India\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"><span class=\"fa fa-phone\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+(91)-0000000000</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\" class=\"mail\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-envelope-open-o\"></span> agricultureinfo@mail.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section class=\"w3l-footer-29-main w3l-copyright\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"bottom-copies\">\r\n");
      out.write("\t\t\t\t<p class=\"copy-footer-29 text-center\">© 2022 Agricultural\r\n");
      out.write("\t\t\t\t\tSystem. All rights reserved.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- move top -->\r\n");
      out.write("\t\t<button onclick=\"topFunction()\" id=\"movetop\" title=\"Go to top\">\r\n");
      out.write("\t\t\t<span class=\"fa fa-angle-up\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t// When the user scrolls down 20px from the top of the document, show the button\r\n");
      out.write("\t\t\twindow.onscroll = function() {\r\n");
      out.write("\t\t\t\tscrollFunction()\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction scrollFunction() {\r\n");
      out.write("\t\t\t\tif (document.body.scrollTop > 20\r\n");
      out.write("\t\t\t\t\t\t|| document.documentElement.scrollTop > 20) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"movetop\").style.display = \"block\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"movetop\").style.display = \"none\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// When the user clicks on the button, scroll to the top of the document\r\n");
      out.write("\t\t\tfunction topFunction() {\r\n");
      out.write("\t\t\t\tdocument.body.scrollTop = 0;\r\n");
      out.write("\t\t\t\tdocument.documentElement.scrollTop = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<!-- /move top -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- //footer-29 block -->\r\n");
      out.write("\t<!-- disable body scroll which navbar is in active -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$('.navbar-toggler').click(function() {\r\n");
      out.write("\t\t\t\t$('body').toggleClass('noscroll');\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- disable body scroll which navbar is in active -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template JavaScript -->\r\n");
      out.write("\t<script src=\"assets/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/theme-change.js\"></script>\r\n");
      out.write("\t<!--/MENU-JS-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(window).on(\"scroll\", function() {\r\n");
      out.write("\t\t\tvar scroll = $(window).scrollTop();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (scroll >= 80) {\r\n");
      out.write("\t\t\t\t$(\"#site-header\").addClass(\"nav-fixed\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#site-header\").removeClass(\"nav-fixed\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//Main navigation Active Class Add Remove\r\n");
      out.write("\t\t$(\".navbar-toggler\").on(\"click\", function() {\r\n");
      out.write("\t\t\t$(\"header\").toggleClass(\"active\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).on(\"ready\", function() {\r\n");
      out.write("\t\t\tif ($(window).width() > 991) {\r\n");
      out.write("\t\t\t\t$(\"header\").removeClass(\"active\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(window).on(\"resize\", function() {\r\n");
      out.write("\t\t\t\tif ($(window).width() > 991) {\r\n");
      out.write("\t\t\t\t\t$(\"header\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--//MENU-JS-->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
