/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2022-04-11 03:26:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class design_002dside_002dheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg stroke\">\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t\t<a class=\"navbar-brand mr-lg-1\" href=\"index.jsp\"> Agricultural<span>\r\n");
      out.write("\t\t\t\tWeb Portal</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</h1>\r\n");
      out.write("\t<button class=\"navbar-toggler  collapsed bg-gradient\" type=\"button\"\r\n");
      out.write("\t\tdata-toggle=\"collapse\" data-target=\"#navbarTogglerDemo02\"\r\n");
      out.write("\t\taria-controls=\"navbarTogglerDemo02\" aria-expanded=\"false\"\r\n");
      out.write("\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t<span class=\"navbar-toggler-icon fa icon-expand fa-bars\"></span> <span\r\n");
      out.write("\t\t\tclass=\"navbar-toggler-icon fa icon-close fa-times\"></span> </span>\r\n");
      out.write("\t</button>\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo02\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.jsp\">Home\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"about.jsp\">About</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"view-crops.jsp\">Crops</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"view-insecticide.jsp\">Insecticides</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"view-equipments.jsp\">Equipments</a></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"view-pesticides.jsp\">Pesticides</a></li>\r\n");
      out.write("\t\t\t<li id=\"menu-item-26\"\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-26 nav-item active dropdown\"><a\r\n");
      out.write("\t\t\t\thref=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\tid=\"navbar-dropdown-menu-link-26\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">Customer</a>\r\n");
      out.write("\t\t\t\t<div class=\"sub-menu dropdown-menu\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"navbar-dropdown-menu-link-26\">\r\n");
      out.write("\t\t\t\t\t<a href=\"customer-login.jsp\" class=\"dropdown-item active\"\r\n");
      out.write("\t\t\t\t\t\tid=\"menu-item-27\">Customer Login</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"customer-account.jsp\" class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\tid=\"menu-item-28\">Customer Account</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li id=\"menu-item-26\"\r\n");
      out.write("\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-26 nav-item active dropdown\"><a\r\n");
      out.write("\t\t\t\thref=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\tid=\"navbar-dropdown-menu-link-26\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">Admin</a>\r\n");
      out.write("\t\t\t\t<div class=\"sub-menu dropdown-menu\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"navbar-dropdown-menu-link-26\">\r\n");
      out.write("\t\t\t\t\t<a href=\"admin-login.jsp\" class=\"dropdown-item active\"\r\n");
      out.write("\t\t\t\t\t\tid=\"menu-item-27\">Admin Login</a> <a href=\"admin-account.jsp\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-item active\" id=\"menu-item-27\">Admin Account</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- toggle switch for light and dark theme -->\r\n");
      out.write("\t<div class=\"mobile-position\">\r\n");
      out.write("\t\t<nav class=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"theme-switch-wrapper\">\r\n");
      out.write("\t\t\t\t<label class=\"theme-switch\" for=\"checkbox\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" id=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"mode-container\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"gg-sun\"></i> <i class=\"gg-moon\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //toggle switch for light and dark theme -->\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
